version: "3.8"

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/front:delegated
      - /app/front/node_modules

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./back:/app/back

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
